### ISSUE TITLE
integration (regression) test CI

### ISSUE THREAD

**Issue by rustdesk** [snooowfire/ironhive#4]
You need to add `main.rs` first to make integation test feasible. windows/linux/mac

**Comment by snooowfire** [comment]
Could you kindly provide me with any appropriate examples I could refer to, akin to the practical example you mentioned in your previous issue  #3 ?

**Comment by rustdesk** [comment]
i do not have an example. but i think the simplest one is testing locally like this bash 

```
install nats
install agent 
send install command to agent via nats to install a software via python script
check if the software installed
```

**Comment by snooowfire** [comment]
After a day of experimentation, I have found the appropriate testing method and have already implemented a [basic test](https://github.com/snooowfire/ironhive/blob/5c557f78695457653a35c2a81b0e60b942a8f24f/src/tests.rs#L12C19-L12C19). In the future, I will add more complex test scenarios and relevant Continuous Integration (CI) processes.

**Comment by rustdesk** [comment]
👍

**Comment by rustdesk** [comment]
It is still not integration test. Integration test is to emulate the prod env.

**Comment by snooowfire** [comment]
I have added integration tests to the code, and you can take a look at them. However, they haven't been integrated into the CI (Continuous Integration) yet because it requires two parts. The first part is to install `nats_server` in the environment before running the integration tests. The second part is to ensure that Python is available in the environment because the scripts used for testing in the integration tests are written in Python.

Regarding the integration tests, you can examine the code [here](https://github.com/snooowfire/ironhive/blob/41a7fdd79c53f1c9c0b6e98e3701c7f9fe377686/examples/integration_test.rs). In fact, it is compiled and then invoked through a script, so it simulates testing in a production environment.

**Comment by snooowfire** [comment]
Also, regarding the reason why the latest code submission hasn't been run in CI (Continuous Integration), there are a few main points. Firstly, the integration of NATS testing is included within the unit tests, which requires `nats_server` to be installed in the environment. Secondly, certain tests require enabling the `deserialize` feature, which is currently not configured for testing. On my local machine, whether it's WSL or the Windows platform, I can run these tests successfully. You can give it a try first to see if it provides the functionality you're looking for, and I'll find a way to add the relevant CI configuration later on.
[fix: check resp with id](https://github.com/snooowfire/ironhive/actions/runs/6577796025)

**Comment by snooowfire** [comment]
@rustdesk 
![image](https://github.com/snooowfire/ironhive/assets/147996737/0159e968-55ae-4cbf-ac68-c6247a04d4ab)
Hello, I have added integration tests, and the project is mostly complete with a few minor bugs. Here are some small bugs that have been identified so far, and they will be gradually fixed in the future:

- [ ] The string conversion of the results queried by the Windows service will cause a crash.
- [ ] Shutdown has not been tested.
- [ ] Some requests require administrator privileges on the host machine.

**Comment by rustdesk** [comment]
👍

**Comment by Cupnfish** [comment]
#6 #7 #8

**Comment by snooowfire** [comment]
I will close this issue as it has already been resolved. The remaining three questions will be tracked and handled as separate issues.

**Comment by rustdesk** [comment]
No problem
